#!/bin/bash

set -e 

message(){
  CYAN="\033[1;36m"
  RED='\033[0;31m'
  YELLOW='\033[1;33m'
  NC='\033[0m' # No Color
  
  if [ $2 == "info" ]; then
    echo -ne "${CYAN} $1 ${NC}\n"
  fi

  if [ $2 == "err" ]; then
    echo -ne "${RED} $1 ${NC}\n"
  fi

  if [ $2 == "warn" ]; then
    echo -ne "${YELLOW} $1 ${NC}\n"
  fi 
} 

message 'Building project' "info"

message '   Resolve dependencies' "info"

if [ -d "node_modules" ]; then
  message '       Dependencies already downloaded' "warn"
else 
  npm install
  message '       Dependencies downloaded' "warn"
fi;

message 'Project Builded' "info"
echo '# To continue just run: npm start'

