#!/bin/bash

set -e
export NODE_ENV=test;

mkdir -p ./coverage

# run the tests
./node_modules/.bin/lab -c -l -r lcov > ./coverage/lab.lcov
# submit to coveralls
cat ./coverage/lab.lcov |  ./node_modules/.bin/coveralls
