#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
scripts/update

test -z "$NODE_ENV" &&
  NODE_ENV='development'

# boot the app and any other necessary processes.
node index.js


